---
version: 2.1


orbs:
  aws-s3: circleci/aws-s3

jobs:
  deploy_bb:
    docker:
      - image: 'circleci/python'
    steps:
      - checkout
      - aws-s3/sync:
          from: html
          to: s3://british-barbell/
          arguments: |
            --delete
            --acl public-read

  deploy_www:
    docker:
      - image: 'circleci/python'
    steps:
      - checkout
      - aws-s3/sync:
          from: html
          to: s3://www.british-barbell.co.uk/
          arguments: |
            --delete
            --acl public-read

workflows:
  version: 2
  build_and_test:
    jobs:

      - deploy_bb:
        filters:
          branches:
            only: master

      - deploy_www:
        filters:
          branches:
            only: master
